name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'GitHub Access Token for accessing the wiki repo'
    required: true
  github-repository:
    description: 'GitHub Repository'
    required: true
  github-sha:
    description: 'git commit SHA'
    required: true
outputs:
  result:
    description: The result of the one-more-time action
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -github-token=${{ inputs.github-token }}
    - -github-repo=${{ inputs.github-repository }}
    - -git-commit=${{ inputs.github-sha }}