name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'GitHub Access Token for accessing the wiki repo'
    required: true
    default: please-set-me
outputs:
  result:
    description: The result of the one-more-time action
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -github-token=${{ inputs.github-token }}
    - -github-repo=${{ github.repository }}
    - -git-commit=${{ github.sha }}